### ISSUE TITLE
Version Installed but not recognized

### ISSUE THREAD

**Issue by ghost** [bikkelbroeders/TouchBarDemoApp#10]
I have the correct version of MacOS running (10.12.1), and yet I get the message:

"We need at least macOS 10.12.1 (build 16GB2657)"

**Comment by pbernery** [comment]
Same here but my build number is 16B2555 whereas the doc indicates 16B2657 is needed.

**Comment by robbertkl** [comment]
Yes, you will need 10.12.1 build 16B2657, this is explained in the README. Version 10.12.2 build 16B2555 does not have Touch Bar support.

Please download build 16B2657 from [this link](https://support.apple.com/kb/dl1897).
