### ISSUE TITLE
swiping

### ISSUE THREAD

**Issue by guloli** [bikkelbroeders/TouchBarDemoApp#101]
it would be a good option to swipe (for example the emojis) with two finguers, because other way its boring to double tap hold ,and swipe until you don't have more screen to move the mouse

**Comment by robbertkl** [comment]
This is just the way the Touch Bar works, and there's nothing we can change about it.

It was designed for 1-finger dragging, since it's supposed to be a touchscreen.

**Comment by guloli** [comment]
thank you  I thought you could change the way it behaves, as it wasn't the same program as the apple touch bar (I mean you can´t change the code
