### ISSUE TITLE
(enhancement) Option to drag the TouchBar around

### ISSUE THREAD

**Issue by netsi1964** [bikkelbroeders/TouchBarDemoApp#104]
Great app! :-)

I would love if it would be possible to drag the TouchBar around the screen, perhaps holding down say CMD and then drag it somewhere. That position should then be remembered.

Thanks

**Comment by robbertkl** [comment]
It will appear wherever your cursor is when you toggle it. So if you need in a different position, just move your mouse to a desired position and press your toggle key twice.
