### ISSUE TITLE
Getting built error

### ISSUE THREAD

**Issue by ghost** [bikkelbroeders/TouchBarDemoApp#12]
When I try to run the app inside a simulator or trying to install it on my iPad I always get the following error:

"Command /Applications/Xcode.app/Contents/Developer/usr/bin/ibtool failed with exit code 255"

**Comment by robbertkl** [comment]
Can you send us the complete error message? And what are the Xcode and iOS versions you're using?

**Comment by robbertkl** [comment]
Since we haven't received any other reports of this, I'm closing this for now.

If you still have this issue, you can reopen or submit a new issue. Be sure to include some more details about the error and your environment (like your versions of macOS, Xcode, iOS).
