### ISSUE TITLE
Feature to Customize the TouchBar

### ISSUE THREAD

**Issue by dieterdemeyer** [bikkelbroeders/TouchBarDemoApp#13]
Hello,

Do you think it would be technically possible to have the ability to customize the TouchBar in different applications like the real TouchBar on the new MacBook Pro ?
Feature wise this would be a great addition, but I'm not sure it's even possible.

**Comment by robbertkl** [comment]
Hi @dieterdemeyer, this is already possible! Our app renders the real Touch Bar, so you can customize it just like the real one.

For most apps, there is now a "Customize Touch Bar..." option in the View menu. Also, in Preferences > Keyboard, there are options for what the Touch Bar shows by default and a button to customize the control strip.

**Comment by dieterdemeyer** [comment]
My bad, I didn't even notice.
I'll definitely check it out.

**Comment by FernandoMiguel** [comment]
@robbertkl where is that?
i cant see it
![screenshot 2016-11-07 15 53 13](https://cloud.githubusercontent.com/assets/168366/20064367/5a6cf694-a502-11e6-845d-665d8a83256d.png)

**Comment by robbertkl** [comment]
Hi @FernandoMiguel, it's a bit different in each app, not all apps have the option.

Here's Safari:

<img width="481" alt="screen shot 2016-11-07 at 19 38 32" src="https://cloud.githubusercontent.com/assets/5704510/20070839/4a72111e-a522-11e6-9445-ce75910eb639.png">

Finder:

<img width="363" alt="screen shot 2016-11-07 at 19 38 56" src="https://cloud.githubusercontent.com/assets/5704510/20070845/54f2421c-a522-11e6-9bc6-6f644fa35e89.png">

System Preferences > Keyboard:

<img width="561" alt="screen shot 2016-11-07 at 19 39 10" src="https://cloud.githubusercontent.com/assets/5704510/20070868/629bf43a-a522-11e6-8030-ee5201fe0734.png">

**Comment by FernandoMiguel** [comment]
@robbertkl 
updated to 1.2 and now it's there.
you guys are moving too fast :)

**Comment by dieterdemeyer** [comment]
@robbertkl Can you also remove items from the TouchBar ?
When following the steps described [here](http://www.imore.com/how-customize-touch-bar-macbook-pro), it doesn't seem to work.. Or does this work in a different way ?

**Comment by AndreasVerhoeven** [comment]
You can just drag items from the Touch Bar using your mouse. We don't control the inner workings of the Touch Bar, we're only making it visible and interactable on an iPad.

**Comment by dieterdemeyer** [comment]
Could it perhaps be an issue when using the On-Screen TouchBar specifically and not the iPad TouchBar Client ?
I've been testing On-Screen TouchBar most of the time.  When adding items, the on-screen touchbar disappears obviously to make room for the list of items you can choose from to add to the TouchBar.

**Comment by robbertkl** [comment]
You're right, that currently blocks the ability to customize it. We might add a permanent on-screen Touch Bar as well; we'll try to have that one stay on screen even in customization mode, if possible.

**Comment by robbertkl** [comment]
@dieterdemeyer The [latest release (v1.3)](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/tag/v1.3) fixes this. The on-screen Touch Bar will now stay on screen, even in customization mode.

Please note that you will still have to drag new buttons to the bottom of the screen, even if your on-screen Touch Bar is floating on the top of your screen, since macOS expects the Touch Bar to be below the display.
