### ISSUE TITLE
Start at Login

### ISSUE THREAD

**Issue by dieterdemeyer** [bikkelbroeders/TouchBarDemoApp#14]
Hello,

When checking **Start at Login** in the menu bar, and then restarting macOS, the TouchBarServer app doesn't seem to be starting on its own.
The app needs to be launched manually to work.

**Comment by robbertkl** [comment]
Hi @dieterdemeyer, did you move the app to your Applications folder? The _Start at Login_ only works when the app resides in `/Applications`.

**Comment by robbertkl** [comment]
It looks like we will be switching to a different method for _Start at Login_, which should fix the issue you're having. I'll close this issue now in favor of #19, please track that issue for the progress.

**Comment by dieterdemeyer** [comment]
@robbertkl , the application is indeed located in the `/Applications` folder.
