### ISSUE TITLE
Command-Tab doesn't seem to function when app is running

### ISSUE THREAD

**Issue by idcrook** [bikkelbroeders/TouchBarDemoApp#15]
Try it when you have the Touch Bar running.
 ⌘-⇥
 It flashes the window showing app list momentarily, then immediately closes it and switch to the app/windows you were already using.

Not sure this is just an anomaly of my system or not.

When I close the Server (and Client) app, the Command-Tab functionality is restored.

**Comment by NetOpWibby** [comment]
I'm not having this issue.

**Comment by robbertkl** [comment]
I can't seem to reproduce this issue. Using either the on-screen and USB Touch Bar, command-tab keeps working fine. Can you try these steps:
1. Reboot your mac and log in
2. Check if command-tab is working properly
3. Start TouchBarServer (don't connect any iOS device yet)
4. Check again if command-tab is still working properly
5. Connect your iOS device running the Touch Bar app
6. Check once more if command-tab is working properly

Please let us now the results of this, and we can look into this.

**Comment by idcrook** [comment]
- [X]  1   Reboot your mac and log in
- [X]  2   Check if command-tab is working properly
- [X]  3   Start TouchBarServer (don't connect any iOS device yet)
- [ ]  4   Check again if command-tab is still working properly **NOPE!**
- [X]  5   Connect your iOS device running the Touch Bar app
- [ ]  6   Check once more if command-tab is working properly  **NOPE!**

Stopped the server. Command-Tab working again.

However, I think I might have discovered what is different in my setup: Keyboard Maestro. See screenshots below.  This seems to affect all the Keyboard Maestro Application/Window  Launcher/Switcher macros. And their "normal" functionality is restored once I close the Server macOS app...  

So it appears something with the keyboard handling on the Server is creating compatibility issues with Keyboard Maestro. Both the `Fn` key on-screen Touch Bar and the iPad Touch Bar work, in any case.

![screenshot 2016-11-08 11 29 30](https://cloud.githubusercontent.com/assets/461806/20111757/af08f6ea-a5a6-11e6-9c9c-43adfe9c3fd6.png)

![screenshot 2016-11-08 10 53 03](https://cloud.githubusercontent.com/assets/461806/20111756/aef88422-a5a6-11e6-89be-efac4b26578f.png)

**Comment by robbertkl** [comment]
What version of TouchBarServer are you running? Can you try the latest ([1.3](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/tag/v1.3))?

**Comment by idcrook** [comment]
I had built from source using latest on master (commit 814bc601b4ab216e54754539b1074d6e2d53af20)

**Comment by idcrook** [comment]
will close this issue as a workaround/possible related cause was identified
