### ISSUE TITLE
Emojis don't work properly

### ISSUE THREAD

**Issue by duraidabdul** [bikkelbroeders/TouchBarDemoApp#16]
When the touch bar is displayed on the Mac, emojis do not show properly, they are cut off at the bottom, and the full emoji list or scroll view is not available

**Comment by robbertkl** [comment]
Can you add a screenshot of this? And please add some additional information like:
- The version of TouchBarServer you're using
- If you're using the on-screen Touch Bar or a USB connected iOS device

Please note we do not control the contents of the Touch Bar, macOS does. We just display it.

**Comment by avaidyam** [comment]
@duraidabdul The "full Emoji list" as previewed during the Apple event is not available yet. Just the smaller recent Emoji list.

**Comment by robbertkl** [comment]
Makes sense, that's why I couldn't find it anywhere :smile:.

Will close this issue then, awaiting Apple's next update.

**Comment by avaidyam** [comment]
@robbertkl Yup! Grab yourself a copy of Hopper and go digging if you'd like. `PrivateFrameworks/DFR*.framework` and `AppKit.framework` will give you all the answers. 😄

**Comment by robbertkl** [comment]
@avaidyam Hehe, yes, that's how and where we found our friends for creating the Touch Bar display stream.
