### ISSUE TITLE
Have to rebuild it

### ISSUE THREAD

**Issue by nick2011** [bikkelbroeders/TouchBarDemoApp#17]
I have to rebuild it every time I wan't to use it.
If I lock my iPad or close the app, I have to rebuild the app using Xcode otherwise I will just get the message:
"Please connect this device ti your Mac and start TouchBarServer..."

**Comment by robbertkl** [comment]
You don't have to rebuild the app. If it's not working, you can also quit the app using the multitasking control (double click the home button and swipe the Touch Bar app upwards). Then it will restart completely and the app will work again.

The issue with locking the iPad has been resolved recently. Please pull the latest version of this repo and rebuild/reinstall the iOS app. After this, locking and unlocking your iPad should function properly.

Please let us know if this works for you, so we can close the issue.

**Comment by nick2011** [comment]
Ok Now it works correctly.
Sorry I missed V1.3 😂
