### ISSUE TITLE
Fn-Key does not work AND an option to position the bar on a static place 

### ISSUE THREAD

**Issue by calaidosCope** [bikkelbroeders/TouchBarDemoApp#18]
Hi. Big Up for this.
My setup: SurfacePro1, Sierra 10.12.1 (16B2555), TBDA 1.2

My  internal fn-Key "reacts" with all the F-keys without a problem. If i press it solo: nothing. Using an "external-keyboard" (Apple-wireless) the Fn-Key works. What about choosing the trigger-key?

And "one more thing": The bar shows up under the mousepointer. In my case (touchscreen) i would like to have it on the lower end of the screen, full width. 

Thanks anyway.

**Comment by robbertkl** [comment]
We're going to add a fixed, full width Touch Bar which sticks to the bottom. As for the Fn-key, it seems your system might use a different keycode. We aim to support only Mac devices, where the Fn-key works fine on both internal keyboards and external Apple keyboards.

Thank you for the suggestion to make the trigger key customizable. I think most people (like you) will switch to the permanent on-screen Touch Bar when that's finished, so the trigger key won't be that important anymore. Besides, this is just a demo app to show the Touch Bar capabilities.

**Comment by calaidosCope** [comment]
Hi. The trigger IS important (for me)! While having a small screen it needs to be turned on and off, to gain space. And hey... ;) ... it is maybe a demo for you. For me it is a full flavored OS X-touch system and a really welcome add-on ... if i can revoke it without the hassle of a onscreen-keyboard or else... ;).

BTW: Using the touchbar on a touchscreen is IMHO more convenient "on the screen" as above the keys... my focus stays where it should be - on screen. I don't need to look at the keyboard while typing, i look at the screen, checking whats going on "above the keys" is interrupting me. OS X is ready for touch... just little corrections need to be done. 
I will post a vid if it works "usable".

**Comment by Randagio13** [comment]
Hi! It's the same for the Logitech Wireless Solar Keyboard K760. 😢

**Comment by m4rouf** [comment]
Yep I have the k760 too and it doesn't work

**Comment by wwdc17** [comment]
Hey... this pull request is adding the "fixed" position touchbar, might be approved soon: https://github.com/bikkelbroeders/TouchBarDemoApp/pull/97

**Comment by wwdc17** [comment]
@m4rouf @iMasterAle @calaidosCope ^^

**Comment by NickHatBoecker** [comment]
@robbertkl Any news on the static position for this tool? Would love to see this

**Comment by AndreasVerhoeven** [comment]
@NickHatBoecker This is a demo tool from 4 years ago, it isn't actively maintained.
