### ISSUE TITLE
TouchBarDemoApp for IOS

### ISSUE THREAD

**Issue by ZXJING** [bikkelbroeders/TouchBarDemoApp#21]
Do anyone develop TouchBarDemoApp for IOS to realize a cool touchbar function with large size and mobility when production on Mac?

**Comment by robbertkl** [comment]
Can you clarify? What are you exactly requesting? The title suggests an iOS app, but we already have this.

**Comment by vincenzoa** [comment]
Hi. This APP is only for MacBook and not for iMac?
Keyboard without FN key

**Comment by AndreasVerhoeven** [comment]
There now is an option to modify the hotkey used in the menu.

**Comment by vincenzoa** [comment]
Great!
