### ISSUE TITLE
Embedded below Dock (make it usable for non- Touch Bar MBPs, etc.)

### ISSUE THREAD

**Issue by alxdxx** [bikkelbroeders/TouchBarDemoApp#25]
Practicality: can it be used everyday? It works great but needs to fit somewhere and moving the Dock from the centre is not ideal.

ideas ++

**Comment by alxdxx** [comment]
Can also try if blacking out left + right of Touch bar can take out 5% of monitor and make the bar permanently occupying the bottom of screen

**Comment by AndreasVerhoeven** [comment]
As much as we would like to do this, it's currently not possible to position the dock offsetted from the screen edges in any way on macOS.

**Comment by alxdxx** [comment]
Could you implement the following?

Place the Touch Bar in the bottom where the Dock is normally (use auto-hide Dock for this example).

When mouse goes to bottom the Dock rises normally, : the Touch Bar disappears and reappears after Dock hides again.

You can do the transition progressive or fixed. Let me know what you think.

Touch Bar is a great addition to the OS for everyone (especially us without the actual TB in a new MBP)

Alex

On 8 Nov 2016, at 23:15, Andreas Verhoeven <notifications@github.com<mailto:notifications@github.com>> wrote:

As much as we would like to do this, it's currently not possible to position the dock offsetted from the screen edges in any way on macOS.
