### ISSUE TITLE
Changing trigger key

### ISSUE THREAD

**Issue by Nataniel4** [bikkelbroeders/TouchBarDemoApp#28]
My keyboard doesn't have a Fn key and I can't see the touchbar. I'm reading the code but I never used Objetive-C, so I can't understand where I need to go for changing the keymap. Can you add an UI option or al least a config file to change it? Thx!

**Comment by robbertkl** [comment]
Coming soon!

**Comment by m4rouf** [comment]
This would be awesome – it would make it possible to assign a mouse button to touch bar :).

**Comment by robbertkl** [comment]
No, actually we're just going to allow the option to change the Fn key to other modifier keys like shift or command.

**Comment by m4rouf** [comment]
Oh. Would it not be possible to set up a keystroke? Some mice can assign buttons to keystrokes but I don't think a single modifier key can be assigned on its own.

**Comment by sonvirgo** [comment]
me too, I can't activate the bar I have PC keyboard and Fn not activate it although my Fn key work with other F1-F12 key

**Comment by robbertkl** [comment]
Just added this!

Either download the source and build the Mac app yourself, or wait for the v1.5 release where this will be included in (along with other features).

**Comment by m4rouf** [comment]
Awesome - thanks!
You should set up a donation page btw

**Comment by robbertkl** [comment]
v1.5 is here, so you can just grab the release version of the server instead of building yourself.

@m4rouf nice suggestion; any recommendations for a github donation service?
