### ISSUE TITLE
Scrolling in TouchBar?

### ISSUE THREAD

**Issue by ghost** [bikkelbroeders/TouchBarDemoApp#31]
Hello,

a short question: Can you change the behavior for scrolling in the TouchBar?

Problem: I am in a mail in Apple Mail. I want to move the mail to a folder in my iCloud. I have many folders, so the field for moving a mail is scrollable. But I can only scroll if I tap and hold the cursor which results that the cursor will be moved left or right with the content. That is annoying, so it would be very useful to can scroll with two fingers (as I scroll content in macOS with the same gesture), so the mouse cursor doesn't move "with" the scrolling. This should be enabled for every type of scrolling content.

I hope you understand what I mean :)

Thank you!

**Comment by AndreasVerhoeven** [comment]
Unfortunately, we have no control over the looks or the interactions on the Touch Bar, so there is not much we can do about that.

**Comment by avaidyam** [comment]
@AndreasVerhoeven Actually this would be trivial to do. It would involve overriding `-wantsScrollEventsForSwipeTrackingOnAxis:` and in `-scrollWheel:` you would translate the event using `-trackSwipeEventWithOptions:dampenAmountThresholdMin:max:usingHandler:`. 

As the handler is invoked, the `NSEventPhase` would help us translate from `-mouseDown:`, `-mouseDragged:`, and `-mouseUp:`, but we would need to repackage the NSEvent or create a CGEvent instead.

EDIT: Or even simpler, just translate `-touchesBeganWithEvent:` and co. instead to mouse events.

**Comment by robbertkl** [comment]
Seems you have  a good idea on how to do this. Could you try it out and, if it works, send us a PR? We'd be happy to take a look.

**Comment by avaidyam** [comment]
@robbertkl I'd love to but the earliest I can get to it would be next week on the account of exams. 👍

**Comment by ghost** [comment]
@avaidyam I would love to see your implementation 👍 It bothers me always to scroll with clicked mouse instead of two-finger gesture 🙈
