### ISSUE TITLE
Use remainder of iPad screen as a touchpad

### ISSUE THREAD

**Issue by humblehacker** [bikkelbroeders/TouchBarDemoApp#32]
Seems to be a natural extension. I found myself accidentally trying to move my screen pointer from the iPad after using the TouchBar for just a few minutes.

**Comment by AndreasVerhoeven** [comment]
As much as we would like to do this, there is no way on macOS to simulate trackpad input at the moment.

See also #26

**Comment by gerwitz** [comment]
Not to beat a dead horse, but could basic gestures be supported?

My (probably very personal) scenario: I use a mouse but still reach to the trackpad for two-finger scroll and three-finger swipe-between-spaces.
