### ISSUE TITLE
iPhone 6s/7 Plus support?

### ISSUE THREAD

**Issue by NicosArv** [bikkelbroeders/TouchBarDemoApp#33]
Haven’t tried but the instructions here on git say can be built to run on iPad. Can you confirm no support for the larger iPhones and If not is there a possibility a slightly shrunken but usable version can be done? Thank you

**Comment by choongjoey** [comment]
i just installed it on my iphone 7 plus, confirmed it to be working but the display is a bit small.

**Comment by AndreasVerhoeven** [comment]
Works out of the box.
