### ISSUE TITLE
Gesture for settings

### ISSUE THREAD

**Issue by par5ul1** [bikkelbroeders/TouchBarDemoApp#34]
Hey, this is more of a customization thing but anyway you could make a settings tab for this which is accessible through a gesture like three finger tap and some settings I can think of are bringing the touchbar to the top portion of the screen and adding custom hex color to the empty area.

**Comment by robbertkl** [comment]
We've decided to keep the iOS app as simple as possible with absolutely _no_ settings. That being said, the settings for the remote Touch Bar clients will be controlled through the server's status menu.

Check out the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest) where you can already align the Touch Bar to different parts of the iOS screen!

**Comment by par5ul1** [comment]
Hey thanks for the reply. How about changing the black color. Can you add that in the settings as well? Just a normal hex color picker would be nice. Thanks.
