### ISSUE TITLE
建议：可以拖拽touchbar到任意位置

### ISSUE THREAD

**Issue by paaboo2013** [bikkelbroeders/TouchBarDemoApp#37]
建议：可以拖拽touchbar到任意位置，方便使用

**Comment by daiweilam** [comment]
只要先按fn讓touchbar隱藏，把滑鼠拖到想放touchbar的位置，再按fn，就可以放到其他地方囉

**Comment by robbertkl** [comment]
Please submit issues in English.

The [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest) adds alignment options for iOS clients.
