### ISSUE TITLE
Overclock

### ISSUE THREAD

**Issue by MekVox** [bikkelbroeders/TouchBarDemoApp#44]
Hi,

when I leave on the touch bar and I put the monitor in stop the CPU goes overclock.
If I quit the Touch Bar Server app, the CPU goes at its normal value.

Could you fix it?
Thanks, M

**Comment by MekVox** [comment]
This issue seems to be fixed with the 1.5 version, thanks!  🙌

**Comment by robbertkl** [comment]
Great!

**Comment by MekVox** [comment]
I'm sorry, the issue still exist.

When I turn off the monitor the fans go fast.
