### ISSUE TITLE
iTunes randomly crash

### ISSUE THREAD

**Issue by sonvirgo** [bikkelbroeders/TouchBarDemoApp#45]
When controlling iTunes with the Touch Bar, minimize, reopen, close iTunes, move back and fort.
iTunes suddenly crash
https://youtu.be/_7t46FPuYN4

**Comment by robbertkl** [comment]
We do not control how applications deal with the Touch Bar or Touch Bar input. If iTunes crashes because of Touch Bar inputs, this is most probably caused by a bug in iTunes.

**Comment by sonvirgo** [comment]
yes I agree, it is very likely as Sierra is not so mature as El Capitan
