### ISSUE TITLE
Holding Fn key on virtual keyboard does not change Touch Bar

### ISSUE THREAD

**Issue by robbertkl** [bikkelbroeders/TouchBarDemoApp#50]
If you hold the Fn key on your physical keyboard, it changes the Touch Bar to show the function keys (this behavior can be modified in System Preferences > Keyboard). However, if you do this on the virtual keyboard on your iOS device, it does not do this.

The same is true for the macOS Keyboard Viewer. Holding the Fn key there does _not_ change what the Touch Bar shows. It sends a proper Fn keydown event to the system, but apparently that's not what the Touch Bar uses to trigger the change.

Does anyone know of any (private) API to trigger this?

**Comment by robbertkl** [comment]
Mentioning @avaidyam since he also checked out the DFR\* frameworks and might have a clue.

**Comment by avaidyam** [comment]
It does have this behavior for the on-screen touchbar, doesn't it? I can take a look at it but I don't have any iOS devices.

**Comment by robbertkl** [comment]
Well, the Touch Bar works fine, at least when you use the physical keyboard, not when using our iOS keyboard or the macOS keyboard viewer. Just open the keyboard viewer and display the on-screen Touch Bar and try holding Fn on the keyboard viewer. No iPad needed (it does exactly the same as the keyboard viewer anyway).

**Comment by avaidyam** [comment]
Ah, I see what you mean. Unfortunately, I think that's a limitation of the emulated keyboard(s) -- when pressing the Fn key, it's not sending a `flags changed` event but when another key is pressed, it then sends the equivalent `Fn+Key` event. I can look into that more later. _Exam in 15 minutes._ 😂

**Comment by robbertkl** [comment]
Actually it _does_ generate a flags changed event. That's why toggling the on-screen Touch Bar does work, even in the keyboard viewer and our virtual iPad keyboard.

The physical keyboard generates the exact same flags changed event, except somehow it also "notifies" the Touch Bar agent to show the function row (or whatever you've setup to show when holding Fn). Perhaps this is done by the TouchBarUserDevice, or maybe the Touch Bar agent is monitoring this by itself. Perhaps there is a private API that we can use to toggle the Touch Bar "secondary state", but so far we've been unable to find it.

Anyway, good luck on your exam! 😄

**Comment by avaidyam** [comment]
Ah I see. I'll take a look at it now, _on account of me probably acing that exam!_ I'll report back in a bit, lol. 😆

**Comment by avaidyam** [comment]
So I believe it has to do with `TouchBarAgent.FnKey` and `TouchBarAgent.UIServer`, but the `TouchBarAgent` binary is primarily Swift. Hopper doesn't do a great job of decompiling into Swift right now, so that's going to be very hard.

**Comment by sonvirgo** [comment]
found this, always work https://red-sweater.com/touche/

**Comment by avaidyam** [comment]
@sonvirgo Disassembling that app shows nothing new or different from this one. 
@robbertkl We could skip a step or two and use the Xcode method which is the `IDE*Simulator` class from the `DRFSupport.framework`.

**Comment by robbertkl** [comment]
@sonvirgo That app has exactly the same behavior when holding Fn on the keyboard viewer: it does _not_ work.

@avaidyam Yeah, we also ran into the Hopper/Swift issue. How would the "Xcode method" help here? Even Xcode's "Show Touch Bar" does not show the function row when holding Fn on the keyboard viewer.
