### ISSUE TITLE
Emoji interface does not work in Touch Bar.

### ISSUE THREAD

**Issue by 17wongam1** [bikkelbroeders/TouchBarDemoApp#53]
When the emoji button is pressed, the system only reports the recent emojis instead of a full list like the MacBook Pro Touch Bar.
![fullsizeoutput_17b8](https://cloud.githubusercontent.com/assets/11416075/20342851/0c1386a8-ac27-11e6-8baa-3ecd212bf0ac.jpeg)
This is what the emoji view **should** be like
[http://i1.wp.com/geekirc.me/wp-content/uploads/2016/10/Touch-Bar-emoji.jpg](url)

**Comment by robbertkl** [comment]
We do not make the content of the Touch Bar, this is controlled by macOS. Apple did not yet release the emoji viewer that they demonstrated during the keynote, so you'll have to wait for that.
