### ISSUE TITLE
IOS App Not Working... Correctly

### ISSUE THREAD

**Issue by jacob-green9** [bikkelbroeders/TouchBarDemoApp#56]
I am using Xcode Version 8, and IOS 10.1.1 on an iPhone 7. I successfully installed the IOS app onto my phone, but instead of just a virtual copy of the touch bar, the app provides me with a picture of the computer, a working keyboard (linking to my computer). Is there anything I am doing wrong or is there a way to fix this so the computer only shows me the touch bar? Thanks pls respond fast if you have any advice.

**Comment by AndreasVerhoeven** [comment]
Hi Jacob,

If you check the menu item of the macOS app, there's an option to toggle between the different modes: one of them is "Touch Bar" only

**Comment by jacob-green9** [comment]
Ahh... thanks so much!
