### ISSUE TITLE
please, i want yo use it on iPhone 6s

### ISSUE THREAD

**Issue by estebanedcm** [bikkelbroeders/TouchBarDemoApp#59]
hi, this app is really awesome
I could install it on my iphone 6s but it looks very small, I would like to see only the keyboard with the touch bar like this
![touchbar](https://cloud.githubusercontent.com/assets/22165907/20377098/460c98c4-ac6b-11e6-9128-4490896335fe.png)

**Comment by robbertkl** [comment]
Check out the status menu, like this:

<img width="588" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5704510/20387844/584ba5f0-acc2-11e6-8e6e-e97b05a1f2e4.png">
