### ISSUE TITLE
Running 10.12.1, but requires 10.12.1

### ISSUE THREAD

**Issue by tracerrx** [bikkelbroeders/TouchBarDemoApp#6]
![image](https://cloud.githubusercontent.com/assets/5452178/20040057/7a14ed9c-a41e-11e6-8edb-19dfcc568a33.png)
![image](https://cloud.githubusercontent.com/assets/5452178/20040061/8ab2e56e-a41e-11e6-9d90-541e8f82d760.png)

**Comment by AndreasVerhoeven** [comment]
Hi,

It requires 10.12.1 (**build 16B2657**), you appear to have build 16B2555, which does not have any Touch Bar capabilities.

> Ensure you have installed [macOS Sierra 10.12.1 build 16B2657 (https://support.apple.com/kb/dl1897), which adds support for the Touch Bar to macOS. **Build 16B2555 does not have Touch Bar support, so it won't work**.

**Comment by robbertkl** [comment]
To see your build number, you can click on the version number on the About This Mac screen.

**Comment by tracerrx** [comment]
That worked... thanks
