### ISSUE TITLE
Does this work with third party apps?

### ISSUE THREAD

**Issue by par5ul1** [bikkelbroeders/TouchBarDemoApp#61]
Hello. So I have just gotten the new FCPX 10.3 but the touch bar does not seem to adapt to it. Is that something to consider? Is this app a port of the touch bar or just a recreation.

**Comment by AndreasVerhoeven** [comment]
This app acts like a mirror of the TouchBar in OSX: we get the image OSX will normally show for the TouchBar and show it on an iPad (or a popup window). 

If an application doesn't show anything on the TouchBar, it simply is not supporting it. From what I read, FCPX 10.3 will only get TouchBar support in 2017.

**Comment by latenitefilms** [comment]
@par5ul1 - Based off this code, I've added Touch Bar support to [FCPX Hacks](https://latenitefilms.com/blog/final-cut-pro-hacks/), which might be of interest?

**Comment by par5ul1** [comment]
@latenitefilms thanks, I have never used FCPX Hacks. What exactly does this do? Also to get the TouchBar support do I just download the new version?
P.S. The app does (did) work with FCPX, I just need to open it with the app open in order for it to recognize it.

**Comment by latenitefilms** [comment]
@par5ul1 - It does a LOT of stuff now, see the blog post for details. Yes, the latest version has Touch Bar support. It's still very much a work-in-progress, but I'm constantly updating it. Any ideas or suggestions welcome!
