### ISSUE TITLE
[IDEA] Touch ID for iPad's with Touch ID.

### ISSUE THREAD

**Issue by par5ul1** [bikkelbroeders/TouchBarDemoApp#63]
Hey, do you think you could unlock the Mac with touch ID like MacID but have it built in? I just saw the Touch Bar on my iPad and the placement of the home button was exactly like the touch Id on the new mac. So do you think that would be a possibility?
Also, thanks for the AMAZING app.

**Comment by robbertkl** [comment]
I'm sorry, this won't be possible. Thanks for the suggestion, though! Glad to hear you enjoy the app.
