### ISSUE TITLE
ld: framework not found DFRFoundation

### ISSUE THREAD

**Issue by BackWorld** [bikkelbroeders/TouchBarDemoApp#64]
when I run the SmartBarServer project, I got the bug of "ld: framework not found DFRFoundation"

**Comment by BackWorld** [comment]
in Xcode8.0

**Comment by DesmondY** [comment]
Make sure you have macOS Sierra 10.12.1 build 16B2657 installed, which adds support for the Touch Bar to macOS.

 10.12.1 build 16B2555 does not have Touch Bar support

It seem that your os version is  10.12.1 build 16B2555

**Comment by BackWorld** [comment]
thanks a lot, I do resolved that problem when I updated my macOS version to latest.
