### ISSUE TITLE
what is this fail?

### ISSUE THREAD

**Issue by pbeneteau** [bikkelbroeders/TouchBarDemoApp#67]
Why did you make the touch bar so small??? It was better before when the bar was displayed in full screen! now we have a macbook picture with a small touch bar... That so bad...

**Comment by robbertkl** [comment]
Why don't you check out the settings in the status menu and change it to the mode you want:

<img width="588" alt="screenshot" src="https://cloud.githubusercontent.com/assets/5704510/20387844/584ba5f0-acc2-11e6-8e6e-e97b05a1f2e4.png">

**Comment by pbeneteau** [comment]
I tried this but it doesn't work for me.

**Comment by robbertkl** [comment]
What doesn't work?
