### ISSUE TITLE
Implement iOS 10 keyboard click sounds on virtual keyboard

### ISSUE THREAD

**Issue by GoldenChaos** [bikkelbroeders/TouchBarDemoApp#68]
iOS 10 introduces new keyboard click sounds with different clicks for different types of keys, which makes touch typing a lot easier.

**Comment by robbertkl** [comment]
Nice suggestion, will definitely do this!

**Comment by robbertkl** [comment]
Fixed in the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest)!
