### ISSUE TITLE
Add software keyboard underneath the Touch Bar on iPad

### ISSUE THREAD

**Issue by GoldenChaos** [bikkelbroeders/TouchBarDemoApp#7]
A software Mac keyboard in the iPad app (*not* the iOS system keyboard) would make my iPad Pro totally usable as a replacement for my magic keyboard. In lieu of tactile feedback, I'd use the iOS keyboard clicks.

For extra credit, use the leftover area above the keyboard for Mission Control-style Spaces management and fast switching.

If a design is needed, I'm a professional UI/UX designer and I'm happy to volunteer for you guys and make one! I'm really interested in controlling my Macs this way.

**Comment by ajkuftic** [comment]
This was the very first thing I thought about when I saw the app. This is pretty much what I want Apple to do for an external Touch Bar enabled keyboard.

Imagine being able to two finger swipe between a regular QWERTY keyboard to an app specific keyboard (like large buttons for Photoshop functions). 

I know there are RSI issues with a pure touchscreen keyboard for long form typing (say, coding), but for the majority of users? I could see this being a really, really useful UI method.

**Comment by AndreasVerhoeven** [comment]
We might have an idea for this. Stay tuned.

**Comment by stipus** [comment]
Bottom of the screen: virtual keyboard
Above keyboard: touch bar
Remaining area on top of the screen: virtual trackpad

This way we can 100% control the mac from a connected iPad

EDIT: Maybe it would be better for practical reasons to have the trackpad area under the virtual keyboard.

**Comment by GoldenChaos** [comment]
@stipus I've used a lot of virtual trackpads and they all suck; they have weird custom pointer acceleration, they're full of stutter and lag, and you can't get force touch. But the nail in the coffin has to be the ergonomics. Because the user can't rest their palms on the iPad, the keyboard must be at the bottom of the iPad's screen to be comfortable to use. This means that there's no good placement for a trackpad... unless you really feel like reaching over the keyboard to move your mouse.

For this reason, I firmly believe the iPad is a noticeably worse trackpad in every way. It's more intuitive and comfortable to use the Magic Trackpad or Magic Mouse I already have.

IMO, all extra real estate should be used in a TouchBar-like way. Mission Control is one possible set of controls that could appear in that area, but theoretically expanded controls could become available for any app or system function if support was built in a-la TouchBar.

@AndreasVerhoeven any way I can get involved?

**Comment by robbertkl** [comment]
We've just added a virtual keyboard to the iOS app! Check out the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest) and let us know what you think.

See the release text about why we haven't added a virtual trackpad, which is similar to what @GoldenChaos said above. We do not have plans for any custom widgets or functionality for the remainder of the screen, as that's not really what this app is meant for. Check out something like [Quadro](http://quadro.me) for this.
