### ISSUE TITLE
Have client app function as a standard USB keyboard (with function keys) when server app is not running

### ISSUE THREAD

**Issue by GoldenChaos** [bikkelbroeders/TouchBarDemoApp#70]
Useful for those times where you've got to restart or log out for any reason.

**Comment by robbertkl** [comment]
I'm sorry, it's not possible for an (non-jailbroken) iPad to act as a USB keyboard. There are ways to mimic a USB device, but they will require a (root) installation and still have a server running, like [this](https://github.com/unbit/foohid). This is not something we want.

Also, remember that this is still a TOUCH BAR demo app, not a generic keyboard replacement (even if some people are using it that way).
