### ISSUE TITLE
Area to left/right of touch bar on virtual keyboard layout should trigger esc/siri

### ISSUE THREAD

**Issue by GoldenChaos** [bikkelbroeders/TouchBarDemoApp#71]
On actual touch bars this area is, in fact, capacitive - at east on the left side, where the empty space can be used to trigger the escape key. It seems like the display is only cut short for symmetry.

Since there's no touch ID sensor on this virtual keyboard, my suggestion is to have both edge areas trigger their respective edge buttons - so escape and Siri by default.

**Comment by robbertkl** [comment]
Fixed in the [latest release](https://github.com/bikkelbroeders/TouchBarDemoApp/releases/latest)!
