### ISSUE TITLE
[Request] Use Tuchpad from iPad

### ISSUE THREAD

**Issue by leo98gomez** [bikkelbroeders/TouchBarDemoApp#75]
In the newest update there are new display options for the Touchbar App. There are ones that show the keyboard and we are able to use the keyboard to type in out MacBooks , then theres some that also show the trackpad. Would it be possible to make the trackpad usable just like the keyboard?

**Comment by AndreasVerhoeven** [comment]
Unfortunately, that isn't possible. There are no APIs in macOS to simulate the track pad.

**Comment by leo98gomez** [comment]
could it be possible to access the TouchBar settings to rearrange the shortcuts, etc. Just like on a MacBook Pro 2016?

**Comment by leo98gomez** [comment]
@AndreasVerhoeven

**Comment by AndreasVerhoeven** [comment]
Yes, this has been answered already in https://github.com/bikkelbroeders/TouchBarDemoApp/issues/13

**Comment by leo98gomez** [comment]
cool thank you
