### ISSUE TITLE
Setup Instructions

### ISSUE THREAD

**Issue by QES** [bikkelbroeders/TouchBarDemoApp#76]
Although obvious it might be useful for those tyro users who think this is a cool tool (it is a great one by they way) to give simple instructions on what to do to compile with Xcode.

ie what to select and how toc hange the bundel identifier and Team Signing user to get it to compile.  Just pointers to people will help them understand what is required and how to do this.  The link to the side loading instructions are a start but it might be more useful to include the basic reminders of what is needed and how to do it in this context directly and then link to them for people who need to do more.

Thanks for a great tool - and wonderful example and demontration of how this technology might be used in the future.

**Comment by midi1996** [comment]
Actually it's quite easy for anyone:

1) Click on Checkout an existing project on the home screen
2) Paste the github link in Download or Clone
3) Let it get the files
4) Check what would you like to compile in the top of the window (next to the Build (play) button) and you'll see the TouchBarClient and Server (client being the mobile device, and Server the mac/hack), click on what you want to compile
5) Select your Team to get the signing certificate
4) Compile using Command + B or the Play button

As I dont have an iOS device, I just compiled the Server part.
You may need to make a free Apple Developer account to get a signing certificate (I think it's mandatory for the iOS build, didnt check)
I get some Stops under the signing part, I dont know what they mean, but it still builds and works good

**Comment by robbertkl** [comment]
We have setup instructions in our README. If these are not sufficient, and you'd like to improve them, a PR is always very welcome.
