### ISSUE TITLE
more Touch bars

### ISSUE THREAD

**Issue by nick2011** [bikkelbroeders/TouchBarDemoApp#8]
I don't know if it's possible but could you split the Touch Bar into multiple lines 
First line the normal FN Keys 
Second line Autocorrection
Third line Emoji's
fourth line often used shortcuts e.g. CMD+C, CMD+V, CMD+X
and maybe an software keyboard

**Comment by AndreasVerhoeven** [comment]
Hi Nick,

Unfortunately, that's not easily doable: the Touch Bar is just a graphical screen where each item could be on a different place depending on a lot of factors: all we see is basically an image.
