### ISSUE TITLE
Emoji on the touchbar incomplete?

### ISSUE THREAD

**Issue by trodriguez** [bikkelbroeders/TouchBarDemoApp#80]
Seems like we don't get the full emoji touchbar with categories, etc. when using this app.  Is everyone else seeing this or am I missing some setting.  I just see a row of emojis but no way to select another set.

**Comment by robbertkl** [comment]
We do not make the content of the Touch Bar, this is controlled by macOS. Apple did not yet release the emoji viewer that they demonstrated during the keynote, so you'll have to wait for that.

**Comment by duraidabdul** [comment]
In all the new Mac reviews I have seen, there are demonstratopmas of the fully functional emoji picker, so I would think there is a way to get them working

**Comment by robbertkl** [comment]
Perhaps, but there's nothing our app can do here. We just display what macOS sends us.

**Comment by trodriguez** [comment]
Ok.  Thanks for a great utility anyway!  Maybe this will work in a future OS update.
