### ISSUE TITLE
Emoji picker

### ISSUE THREAD

**Issue by duraidabdul** [bikkelbroeders/TouchBarDemoApp#81]
I know it is claimed that the complete emoji picker hasn't been implemented in the new macOS version, but I'm pretty sure it has been, because in the video demo it shows up (at 1:17) https://www.youtube.com/watch?v=RZLx03OPpUU

Also, it shows up in the reviews for the new MacBook Pro

**Comment by robbertkl** [comment]
The contents of the Touch Bar display are not controlled by the app. MacOS does this.
