### ISSUE TITLE
Fullscreen

### ISSUE THREAD

**Issue by duraidabdul** [bikkelbroeders/TouchBarDemoApp#85]
Would it be possible to have the touchbar only work on the desktop so that it doesn't obstruct the display of fullscreen apps and videos? It did this in an earlier version, but I was wondering if it would be possible to add a toggle to enable/disable it in fullscreen, and have it only function on the desktop like before

**Comment by Tan-the-Man** [comment]
You can, all you have to do is toggle the fn key on your keyboard.

**Comment by duraidabdul** [comment]
I mean automatically, kind of like the dock
