### ISSUE TITLE
[Suggestion] Allow physical function keys to control on screen touch bar

### ISSUE THREAD

**Issue by joel0063** [bikkelbroeders/TouchBarDemoApp#90]
It would be *very* cool if the physical function keys could correspond to the on-screen touch bar controls. Of course, some scaling would be required so that the touch bar is the same size as the physical keyboard.

**Comment by robbertkl** [comment]
The Touch Bar has different visualizations every time, which doesn't correspond to the physical buttons. It allows dragging and multi-touch, which is impossible with the keys.

Also, overriding the function keys is not something we want for a Touch Bar demo app.
