### ISSUE TITLE
Does not show up on 10.2.2 (16C67)

### ISSUE THREAD

**Issue by crunchtime-ali** [bikkelbroeders/TouchBarDemoApp#92]
I've got a Touch Bar MBPro and would like to use this app to record a video including the touchbar for YouTube but after opening the tool and pressing FN the window does not show up. 
Is this related to me installing 10.2.2 ?

**Comment by robbertkl** [comment]
No, the app should still work on 10.2.2. Did the tool work before on the same laptop?

**Comment by crunchtime-ali** [comment]
It only started to work after setting this option to "extend control strip"

![tastatur 2017-01-15 16-06-37](https://cloud.githubusercontent.com/assets/7140800/21963509/9f0674ea-db3c-11e6-8ee3-f3e108813887.png)
